export const GGCLASS = 'material-symbols-rounded';

/**
 * Verified Material Symbols Rounded ligature names (FR-036).
 * ≥150 entries across navigation, actions, communication, content,
 * editor, files, hardware, image, maps, social, and status categories.
 * Source: https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints
 */
export const GGICONS = {
    // ── Core (original — preserved exactly) ──────────────────────────────────
    ADD:                'add_2',
    REMOVE:             'remove',
    VISIBILITY:         'visibility',
    VISIBILITY_OFF:     'visibility_off',
    SEARCH:             'search',
    CALENDAR:           'calendar_month',
    CLOSE:              'close',
    CANCEL:             'cancel',
    CHECK:              'check',
    MAIL:               'mail',
    PHONE:              'phone',
    CREDIT_CARD:        'credit_card',
    ARROW_UP:           'keyboard_control_key',
    ARROW_LEFT:         'arrow_left',
    INFO:               'info_i',
    WARNING:            'warning',
    SELECT_CHECKBOX:    'select_check_box',
    SELECT_VOID:        'select',
    SELECT_ALL:         'select_all',
    DELETE:             'delete',
    REFRESH:            'cached',
    SAVE:               'save',
    SAVE2:              'save_as',
    DEVICES:            'devices',

    // ── Navigation ───────────────────────────────────────────────────────────
    HOME:               'home',
    MENU:               'menu',
    MENU_OPEN:          'menu_open',
    ARROW_BACK:         'arrow_back',
    ARROW_FORWARD:      'arrow_forward',
    ARROW_UPWARD:       'arrow_upward',
    ARROW_DOWNWARD:     'arrow_downward',
    ARROW_RIGHT:        'arrow_right',
    CHEVRON_LEFT:       'chevron_left',
    CHEVRON_RIGHT:      'chevron_right',
    EXPAND_MORE:        'expand_more',
    EXPAND_LESS:        'expand_less',
    OPEN_IN_NEW:        'open_in_new',
    FULLSCREEN:         'fullscreen',
    FULLSCREEN_EXIT:    'fullscreen_exit',
    FIRST_PAGE:         'first_page',
    LAST_PAGE:          'last_page',
    MORE_VERT:          'more_vert',
    MORE_HORIZ:         'more_horiz',
    APPS:               'apps',
    DASHBOARD:          'dashboard',
    GRID_VIEW:          'grid_view',
    VIEW_LIST:          'view_list',
    VIEW_MODULE:        'view_module',
    NAVIGATE_BEFORE:    'navigate_before',
    NAVIGATE_NEXT:      'navigate_next',

    // ── Actions ───────────────────────────────────────────────────────────────
    EDIT:               'edit',
    SHARE:              'share',
    DOWNLOAD:           'download',
    UPLOAD:             'upload',
    PRINT:              'print',
    CONTENT_COPY:       'content_copy',
    CONTENT_PASTE:      'content_paste',
    CONTENT_CUT:        'content_cut',
    LINK:               'link',
    LINK_OFF:           'link_off',
    SETTINGS:           'settings',
    TUNE:               'tune',
    FILTER_LIST:        'filter_list',
    FILTER_ALT:         'filter_alt',
    SORT:               'sort',
    SWAP_VERT:          'swap_vert',
    SWAP_HORIZ:         'swap_horiz',
    UNDO:               'undo',
    REDO:               'redo',
    LAUNCH:             'launch',
    ZOOM_IN:            'zoom_in',
    ZOOM_OUT:           'zoom_out',
    OPEN_IN_BROWSER:    'open_in_browser',
    BUILD:              'build',
    MANAGE_SEARCH:      'manage_search',
    DRAG_INDICATOR:     'drag_indicator',
    DRAG_HANDLE:        'drag_handle',
    CLEAR_ALL:          'clear_all',
    ADD_CIRCLE:         'add_circle',
    REMOVE_CIRCLE:      'remove_circle',

    // ── Selection ─────────────────────────────────────────────────────────────
    RADIO_CHECKED:      'radio_button_checked',
    RADIO_UNCHECKED:    'radio_button_unchecked',
    TOGGLE_ON:          'toggle_on',
    TOGGLE_OFF:         'toggle_off',
    INDETERMINATE:      'indeterminate_check_box',

    // ── Communication ─────────────────────────────────────────────────────────
    CHAT:               'chat',
    MESSAGE:            'message',
    FORUM:              'forum',
    SMS:                'sms',
    SEND:               'send',
    REPLY:              'reply',
    FORWARD_MSG:        'forward',
    NOTIFICATIONS:      'notifications',
    NOTIFICATIONS_OFF:  'notifications_off',
    CALL:               'call',
    VIDEOCAM:           'videocam',
    VIDEOCAM_OFF:       'videocam_off',
    CONTACT_MAIL:       'contact_mail',
    CONTACT_PHONE:      'contact_phone',
    EMAIL:              'email',
    INBOX:              'inbox',

    // ── Content ───────────────────────────────────────────────────────────────
    ARCHIVE:            'archive',
    UNARCHIVE:          'unarchive',
    REPORT:             'report',
    FLAG:               'flag',
    BOOKMARK:           'bookmark',
    BOOKMARK_BORDER:    'bookmark_border',
    LABEL:              'label',
    LIST_ALT:           'list_alt',
    NOTE_ADD:           'note_add',
    DESCRIPTION:        'description',
    ASSIGNMENT:         'assignment',
    ARTICLE:            'article',
    FEED:               'feed',
    LIBRARY_BOOKS:      'library_books',
    TOPIC:              'topic',
    INVENTORY:          'inventory_2',

    // ── Editor ────────────────────────────────────────────────────────────────
    FORMAT_BOLD:            'format_bold',
    FORMAT_ITALIC:          'format_italic',
    FORMAT_UNDERLINED:      'format_underlined',
    FORMAT_LIST_BULLETED:   'format_list_bulleted',
    FORMAT_LIST_NUMBERED:   'format_list_numbered',
    TITLE:                  'title',
    TEXT_FIELDS:            'text_fields',
    ATTACH_FILE:            'attach_file',
    IMAGE:                  'image',
    TABLE_CHART:            'table_chart',

    // ── Files ─────────────────────────────────────────────────────────────────
    FOLDER:             'folder',
    FOLDER_OPEN:        'folder_open',
    FOLDER_SHARED:      'folder_shared',
    CLOUD_UPLOAD:       'cloud_upload',
    CLOUD_DOWNLOAD:     'cloud_download',
    UPLOAD_FILE:        'upload_file',
    DRIVE_RENAME:       'drive_file_rename_outline',
    INSERT_DRIVE_FILE:  'insert_drive_file',

    // ── Hardware ──────────────────────────────────────────────────────────────
    KEYBOARD:           'keyboard',
    TABLET:             'tablet',
    SMARTPHONE:         'smartphone',
    COMPUTER:           'computer',
    HEADSET:            'headset',
    SCANNER:            'scanner',
    CAMERA:             'camera_alt',
    ROUTER:             'router',

    // ── Image & Media ─────────────────────────────────────────────────────────
    PHOTO:              'photo',
    PHOTO_LIBRARY:      'photo_library',
    CROP:               'crop',
    PALETTE:            'palette',
    BRUSH:              'brush',
    CONTRAST:           'contrast',
    ROTATE_RIGHT:       'rotate_90_degrees_cw',
    PLAY_ARROW:         'play_arrow',
    PAUSE:              'pause',
    STOP:               'stop',

    // ── Maps & Location ───────────────────────────────────────────────────────
    LOCATION_ON:        'location_on',
    PLACE:              'place',
    DIRECTIONS:         'directions',
    MAP:                'map',
    NEAR_ME:            'near_me',
    GPS_FIXED:          'gps_fixed',

    // ── Social ────────────────────────────────────────────────────────────────
    PERSON:             'person',
    GROUP:              'group',
    GROUP_ADD:          'group_add',
    PEOPLE:             'people',
    PERSON_ADD:         'person_add',
    PERSON_REMOVE:      'person_remove',
    PUBLIC:             'public',
    WORK:               'work',
    ACCOUNT_CIRCLE:     'account_circle',
    BADGE:              'badge',

    // ── Status & Feedback ─────────────────────────────────────────────────────
    ERROR_OUTLINE:      'error_outline',
    HELP_OUTLINE:       'help_outline',
    LOCK:               'lock',
    LOCK_OPEN:          'lock_open',
    VERIFIED:           'verified',
    WARNING_AMBER:      'warning_amber',
    PENDING:            'pending',
    HOURGLASS_TOP:      'hourglass_top',
    BLOCK:              'block',
    CHECK_CIRCLE:       'check_circle',
    DONE:               'done',
    DONE_ALL:           'done_all',
    STARS:              'stars',
    THUMB_UP:           'thumb_up',
    THUMB_DOWN:         'thumb_down',

    // ── Finance & Commerce ────────────────────────────────────────────────────
    SHOPPING_CART:      'shopping_cart',
    STOREFRONT:         'storefront',
    RECEIPT:            'receipt',
    PAYMENTS:           'payments',
    ATTACH_MONEY:       'attach_money',
    PERCENT:            'percent',
    POINT_OF_SALE:      'point_of_sale',
    LOYALTY:            'loyalty',

    // ── Date & Time ───────────────────────────────────────────────────────────
    SCHEDULE:           'schedule',
    ACCESS_TIME:        'access_time',

    // ── Color ─────────────────────────────────────────────────────────────────
    COLOR_LENS:         'color_lens',
    INVERT_COLORS:      'invert_colors',    LIGHT_MODE:         'light_mode',
    DARK_MODE:          'dark_mode',
    // ── Tags ──────────────────────────────────────────────────────────────────
    LOCAL_OFFER:        'local_offer',
    SELL:               'sell',
} as const;

export type GGIconKey = keyof typeof GGICONS;

export default GGICONS;

